<?xml version="1.0" encoding="UTF-8"?><testrun name="WebsiteAnalyzerTest" project="AdChallengeWEbanalyzer" tests="5" started="5" failures="1" errors="0" ignored="0">
  <testsuite name="com.adchallenge.test.WebsiteAnalyzerTest" time="0.0">
    <testcase name="validateSizeMaximum" classname="com.adchallenge.test.WebsiteAnalyzerTest" time="0.0"/>
    <testcase name="validateSizeAllSame" classname="com.adchallenge.test.WebsiteAnalyzerTest" time="0.0"/>
    <testcase name="validateSizeWithNullUrl" classname="com.adchallenge.test.WebsiteAnalyzerTest" time="0.0">
      <failure>java.lang.AssertionError: &#13;
	at org.junit.Assert.fail(Assert.java:71)&#13;
	at org.junit.Assert.assertTrue(Assert.java:34)&#13;
	at org.junit.Assert.assertTrue(Assert.java:43)&#13;
	at com.adchallenge.test.WebsiteAnalyzerTest.validateSizeWithNullUrl(WebsiteAnalyzerTest.java:64)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&#13;
	at java.lang.reflect.Method.invoke(Method.java:497)&#13;
	at org.junit.internal.runners.TestMethodRunner.executeMethodBody(TestMethodRunner.java:99)&#13;
	at org.junit.internal.runners.TestMethodRunner.runUnprotected(TestMethodRunner.java:81)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)&#13;
	at org.junit.internal.runners.TestMethodRunner.runMethod(TestMethodRunner.java:75)&#13;
	at org.junit.internal.runners.TestMethodRunner.run(TestMethodRunner.java:45)&#13;
	at org.junit.internal.runners.TestClassMethodsRunner.invokeTestMethod(TestClassMethodsRunner.java:66)&#13;
	at org.junit.internal.runners.TestClassMethodsRunner.run(TestClassMethodsRunner.java:35)&#13;
	at org.junit.internal.runners.TestClassRunner$1.runUnprotected(TestClassRunner.java:42)&#13;
	at org.junit.internal.runners.BeforeAndAfterRunner.runProtected(BeforeAndAfterRunner.java:34)&#13;
	at org.junit.internal.runners.TestClassRunner.run(TestClassRunner.java:52)&#13;
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)&#13;
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)&#13;
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="validateize" classname="com.adchallenge.test.WebsiteAnalyzerTest" time="0.0"/>
    <testcase name="validateizeEmpty" classname="com.adchallenge.test.WebsiteAnalyzerTest" time="0.0"/>
  </testsuite>
</testrun>
